### ISSUE TITLE
Suggestion: Remove High Velocity Rounds from loot spawns.

### ISSUE THREAD

**Issue by MarshalRed** [DS-13-Dev-Team/DS13-1.0#1481]

**Comment by NanakoAC** [comment]
they were actually made more obtainable after repeated requests from players, people love them and want to use them more. multiple ammotypes gives players more options and choice.

HV rounds may still be rebalanced, their rarity is adjustable, their power might be nerfed. But they will remain in random loot and they're getting added to the store too (pretty expensive though)

Also, not balance related but from a lore perspective, HV rounds are really just ordinary bullets.
The standard pulse rounds are intentionally depowered subsonic rounds, designed to be safe for use aboard space vessels, weakened so that they don't break windows and cause breaches
