### ISSUE TITLE
Suggestion: Reduce Engineering RIG slowdown

### ISSUE THREAD

**Issue by Icedcabbage** [DS-13-Dev-Team/DS13-1.0#1506]
#### Suggestion:
Reduce Engineering RIG slowdown so it moves as fast as other light RIGs like the Advanced RIG. Right now the Engineering RIG has the same amount of protection as Hacker RIG or Firesuit RIG and moves slower than both. Since the Engineering RIG has so little armor I feel it should move as fast as other lighter RIGs who have the same amount of armor.

#### What do you think it'd add:
It will allow the Engineering RIG to be more useful in its intended job of giving the Engineer some protection as they fix things, also the description of the Engineering RIG describes it as lightweight so it would make that make more sense.

**Comment by NanakoAC** [comment]
making it as fast as the advanced rig would be nonsensical, advanced rig's defining trait is that its lighter than others

More likely is either buffing the armor of engineering rig, or weakening the firesuit one, latter seems too strong

**Comment by Survivor23** [comment]
I suggest buffing the resistances back to their old values. They were lowered to balance the expansion to the amount of available RIGs. Now that security needs code red to access their rigs, and that most of the available RIGs are relatively weak in terms of protection, engineering RIGs would be a good middle ground due to their slow speeds yet canonical bulkiness.
