### ISSUE TITLE
Suggestion: Necro Tiering

### ISSUE THREAD

**Issue by YellowKingThe** [DS-13-Dev-Team/DS13-1.0#1672]
#### Suggestion:
Necro uptiering should be based on biomass spent instead of on biomass accumulated total.

#### What do you think it'd add:
It will encourage necros to spend biomass instead of horde it for single big necros, or multiple big necros, it will become encouraged to build more smaller necros to help tier up and so they can't save up a huge surplus to spam out hunters and other large necros instead of making necros with their bio.

**Comment by DTraitor** [comment]
I like this one

**Comment by lamesace** [comment]
this is a really really good one

**Comment by NanakoAC** [comment]
Total biomass was added in response to people wanting tiers the first time.  It tests your total performance as the marker, obtaining biomass is the primary goal

Spending it is a different matter. Blindly spending every gram of biomass you get is not an intended goal, and encouraging that doesn't make for great gameplay. It leads to just spamming whatever the cheapest is as soon as they're available to crank out endless swarms, in the process depreciating variety.

And if you're thinking of specifically -spent- rather than currently allocated biomass, that would create a perverse incentive to spam exploders again because they have a faster biomass recovery time

Marker gameplay is intentionally left open ended for people to develop their own strategies. This idea seems like a step away from that, and would narrow the range of viable playstyles. I'm not seeing benefits
