### ISSUE TITLE
BUG: Necromorphs can be trapped in bear traps... forever!

### ISSUE THREAD

**Issue by Ketrai** [DS-13-Dev-Team/DS13-1.0#171]
#### Description of issue
Necros can't escape bear traps. (they can't use them, lacking dexterity)

#### Difference between expected and actual behavior
Necros no booli

#### Steps to reproduce 
Step in a bear trap as a necro, cry.

**Comment by ghost** [comment]
![clonk](https://user-images.githubusercontent.com/44979174/77239315-65e40280-6bd1-11ea-80a3-50dc1555c653.png)

Because necros can't interact with traps to unbuckle themselves, it doesn't seem like they can escape. The Ubermorph had to cut it's own legs off to get out, and the other morphs just straight up eventually died.

**Comment by Snypehunter007** [comment]
This one and #172 could honestly be combined.

On top of that, I'm not really sure we need bear traps. They don't really make sense for the setting overall or to be on the Ishimura.

**Comment by ghost** [comment]
> On top of that, I'm not really sure we need bear traps. They don't really make sense for the setting overall or to be on the Ishimura.

It applies to the craftable improvised traps too.
