### ISSUE TITLE
[Suggestion] Make necromorphs' extended view toggelable

### ISSUE THREAD

**Issue by SailieVN** [DS-13-Dev-Team/DS13-1.0#239]
> #### Description of suggestion
> Make it so that the extended view range for some necros (like leaper, twitcher, etc.) can be toggled back to regular view range. It's very difficult to fight when the view is jumping around every time you change direction.

**Comment by NanakoAC** [comment]
I know its difficult to fight, that's a deliberate weakness of the leaper :P He is made for longrange ambushing, not standing and tanking people.

The twitcher is, by design, a chaotic, disorienting dance, for both people involved. It's intended to evoke a "wtf was that" reaction, and it seems to work quite well. In terms of practical results, the twitcher is also performing pretty well in combat, thanks to their step strike and evasion, they don't really need to be made easier

That said, i do have a plan to code an alternate implementation of view offset, which works by blacking out parts of the screen instead of shifting things. We'll see how things go after that

**Comment by Ketrai** [comment]
issue is leaper can't really follow up on an ambush, and is too slow to escape after.
