### ISSUE TITLE
[Suggestion] Planetside Marker should activate at 30 minutes, while shards activate at 45

### ISSUE THREAD

**Issue by TheMaskedMan2** [DS-13-Dev-Team/DS13-1.0#304]
Well to be honest I think 45 is much too long to wait to see any appearance at all of the main opposing force. There's also the problem that I believe the surface is unused in favor of jumping straight to the stealthy ishimura shards and not abandoning biomass on an empty planet.

So there will be a ramp up of Necros appearing on the planet before the ship.

Perhaps activation phases? Starts off weaker, powers up further, can spread to shards, etc. Something like that.

To be honest I would even maybe make it 25 and 40.

**Comment by TheMaskedMan2** [comment]
I'm just going to add this to that.

Necromorph gameplay is really slow, there is way too much downtime as Necro. 45 minutes waiting. Spawns every 10 minutes, it's really slow.

Biomass gain is slow.

Nests spawn a single slasher every 7 minutes? You have multiple people fighting over it, but probably multiple nests so let's say 10 mins.

By the time the round reaches 1:30 youve been able to play necro 3 times, I get it's not supposed to be super fast paced but with how disposable necros feel it's a bit lame at times to essentially be afk as a signal. There's a lot, lot more waiting than fighting unless Necros suddenly get some free spawns and then they snowball with unlimited biomass. It's weird. Not claiming to be super well-versed in it.

But I feel like there's something just needlessly slow about it. I will say it DOES start to ramp up really nicely, but by the time its ramping up all the humans are kind of dead and it's a tad lame.

The start just feels very slow, so either the start needs to be quicker or start the marker sooner, cause it's gonna take em 30 mins to become a threat anyways. I notice this a lot more when there's no admin spawn shenanigans going on or injections of biomass.

With multiple rounds with zero admin injection of Necros or Biomass, Necromorphs rarely got beyond spawning only slashers, with the max I saw being four slashers alive at 1:42 in.

Necros at the moment feel as if they are designed to very very slowly ramp up over the course of a long round, but they don't have the time needed to ramp up with them only activating so late into the round.

**Comment by NanakoAC** [comment]
its worth noting that necromorphs still consistently win once they get rolling and everyone starts playing. The humans are currently not powerful enough to handle more necromorphs

Theres a lot of people that want to play necros because its new and original, far more than there are trained combatants on the human side. this is something i'll try to keep an eye on over time. Generally the humans need to have a chance. Any solution of just implementing more biomass or more necromorphs right now will see the humans steamrolled even harder, the slow buildup is important

The myriad of signal abilities is meant to be the stopgap, giving the signals stuff to do while they wait, and to help cultivate the horror atmosphere. There is a consensus among senior staff, especially from west himself, that we want the game to be slower, not faster.

There are lots of problems to deal with yet, especially the humans evac-ing so early and ending it as soon as things get rough. one issue is all the people who observe and join necromorphs at roundstart. Creating huge competition for the biomass. If almost-everyone would play a human first, and join necromorphs after they die, things would even out a lot more, since your own corpse would provide biomass for something playable

As to the headline issue, i agree that planetside activation first - and shards later - would be a good thing. not sure i agree about the specified times, thats something to discuss

**Comment by NanakoAC** [comment]
We discussed this in staff chat, you were included, the consensus seems to be that earlier planetside activation wouldn't help much at present. The miners are still cowards who flee at the first sign of trouble, and this would just result in necromorphs running around bored for 15 minutes on an empty planet

something to revisit when we find more ways to make those miners do their job
