### ISSUE TITLE
Suggestion: Remove weapon durability

### ISSUE THREAD

**Issue by DarkPR** [DS-13-Dev-Team/DS13-1.0#560]

**Comment by NanakoAC** [comment]
Durability is an intentional design choice. The humans are powerful, but limited in resources.  Limitations like this are a common aspect of survival horror. You might notice that quite a lot of guns can wipe out a necromorph in a single hit, but have very little ammo.
The necromorphs start off weak, but are essentially immune to attrition, their power can only increase over time as they recover the biomass spent on anything that gets destroyed, while still gaining more.

The humans' goal is to stall for time, keep the ship running and survive long enough to escape, not to fight an endless battle. Combat is a risk, it comes with a cost, and eventually you will lose if it goes on long enough

That's not to say everything is perfect right now. Weapon durability may be improved, repairs made easier, etc.  And i will probably make things become unusuable, rather than being deleted, when they break.
There will certainly be balance changes. But the core concept : your stuff can break, is here to stay
