### ISSUE TITLE
[BUG] Lung Damage out the wazoo

### ISSUE THREAD

**Issue by JakeDaBoss** [DS-13-Dev-Team/DS13-1.0#940]
#### Description of issue:
 Lung collapse or puncture is accrued .1 seconds after being exposed to vacuum. This is not realistic, and quite a killer.

#### Difference between expected and actual behavior:
Lung collapse or puncture accrued over time. Spending 2 seconds in vacuum, got me up to 24 damage out of 75 max.

#### Steps to reproduce:
Stand in a vacuum, watch the variables.

**Comment by Snypehunter007** [comment]
It technically is _realistic_, which is what I believe Bay was going for. Due to pressure differences, if someone was rapidly exposed to a vacuum (via, say, sudden decompression) while they had air in their lungs, the pressure difference would cause the air in their lungs to rapidly expand before the lung, which is essentially an organic balloon, would pop.

Apparently the noise of the a lung popping, though you would technically be unable to hear it in space, is pretty sickening sounding. You could theoretically reduce the chance of your lungs popping by immediately expelling all air from your lungs, but then you would just suffocate sooner.

Getting away from _realism_, in terms of gameplay, it might be worthwhile to increase the time before lung collapse a little bit, though it should probably still happen relatively quickly.

**Comment by Snypehunter007** [comment]
@JakeDaBoss Did you test this with no vacuum protection on?

**Comment by JakeDaBoss** [comment]
> @JakeDaBoss Did you test this with no vacuum protection on?

Correct.
